// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "ctre/Phoenix.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "WPILib.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainLeftFront;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainLeftBack;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainRightFront;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainRightBack;
std::shared_ptr<frc::SpeedController> RobotMap::armArmActuator;
std::shared_ptr<frc::AnalogPotentiometer> RobotMap::armArmPositionSensor;
std::shared_ptr<frc::SpeedController> RobotMap::intakeLeftRoller;
std::shared_ptr<frc::SpeedController> RobotMap::intakeRightRoller;
std::shared_ptr<frc::SpeedController> RobotMap::climberClimberRelease;
std::shared_ptr<frc::SpeedController> RobotMap::climberClimberPullMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    driveTrainLeftFront.reset(new WPI_TalonSRX(0));
    
    
    driveTrainLeftBack.reset(new WPI_TalonSRX(1));
    
    
    driveTrainRightFront.reset(new WPI_TalonSRX(2));
    
    
    driveTrainRightBack.reset(new WPI_TalonSRX(3));
    
    
    armArmActuator.reset(new frc::VictorSP(2));
    lw->AddActuator("Arm", "ArmActuator", std::static_pointer_cast<frc::VictorSP>(armArmActuator));
    
    armArmPositionSensor.reset(new frc::AnalogPotentiometer(0, 1.0, 0.0));
    lw->AddSensor("Arm", "ArmPositionSensor", armArmPositionSensor);
    
    intakeLeftRoller.reset(new frc::VictorSP(0));
    lw->AddActuator("Intake", "LeftRoller", std::static_pointer_cast<frc::VictorSP>(intakeLeftRoller));
    
    intakeRightRoller.reset(new frc::VictorSP(1));
    lw->AddActuator("Intake", "RightRoller", std::static_pointer_cast<frc::VictorSP>(intakeRightRoller));
    
    climberClimberRelease.reset(new frc::VictorSP(4));
    lw->AddActuator("Climber", "ClimberRelease", std::static_pointer_cast<frc::VictorSP>(climberClimberRelease));
    
    climberClimberPullMotor.reset(new frc::VictorSP(3));
    lw->AddActuator("Climber", "ClimberPullMotor", std::static_pointer_cast<frc::VictorSP>(climberClimberPullMotor));
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    driveTrainLeftBack->Follow(*driveTrainLeftFront); //left back to follow left front
     driveTrainRightBack->Follow(*driveTrainRightFront); //right back to follow right front

     driveTrainLeftFront->SetSensorPhase(true); //Reverse sensors
     driveTrainRightFront->SetSensorPhase(true); //Reverse sensors

     driveTrainRightBack->SetInverted(true); //Reverse motor and slave for right side of robot.
     driveTrainRightFront->SetInverted(true);

     driveTrainLeftFront->ConfigSelectedFeedbackSensor(FeedbackDevice::QuadEncoder, 0, kTimeoutMs);
     driveTrainRightFront->ConfigSelectedFeedbackSensor(FeedbackDevice::QuadEncoder, 0, kTimeoutMs);

     /*
      * Set Neutral modes to brake
      */


     driveTrainLeftFront->SetNeutralMode(NeutralMode::Brake);
     driveTrainLeftBack->SetNeutralMode(NeutralMode::Brake);
     driveTrainRightFront->SetNeutralMode(NeutralMode::Brake);
     driveTrainRightBack->SetNeutralMode(NeutralMode::Brake);



     /* Configure PID_F for Closed Loop */

     driveTrainLeftFront->Config_kF(kSlotIDx_Cloop, kF_CloopLeft, kTimeoutMs);
     driveTrainLeftFront->Config_kP(kSlotIDx_Cloop, kP_CloopLeft, kTimeoutMs);
     driveTrainLeftFront->Config_kI(kSlotIDx_Cloop, kI_CloopLeft, kTimeoutMs);
     driveTrainLeftFront->Config_kD(kSlotIDx_Cloop, kD_CloopLeft, kTimeoutMs);

     driveTrainRightFront->Config_kF(kSlotIDx_Cloop, kF_CloopRight, kTimeoutMs);
     driveTrainRightFront->Config_kP(kSlotIDx_Cloop, kP_CloopRight, kTimeoutMs);
     driveTrainRightFront->Config_kI(kSlotIDx_Cloop, kI_CloopRight, kTimeoutMs);
     driveTrainRightFront->Config_kD(kSlotIDx_Cloop, kD_CloopRight, kTimeoutMs);

     /*Configure PID_F for Motion Profile */

     driveTrainLeftFront->Config_kF(kSlotIDx_Motion, kF_MotionLeft, kTimeoutMs);
     driveTrainLeftFront->Config_kP(kSlotIDx_Motion, kP_MotionLeft, kTimeoutMs);
     driveTrainLeftFront->Config_kI(kSlotIDx_Motion, kI_MotionLeft, kTimeoutMs);
     driveTrainLeftFront->Config_kD(kSlotIDx_Motion, kD_MotionLeft, kTimeoutMs);

     driveTrainRightFront->Config_kF(kSlotIDx_Motion, kF_MotionRight, kTimeoutMs);
     driveTrainRightFront->Config_kP(kSlotIDx_Motion, kP_MotionRight, kTimeoutMs);
     driveTrainRightFront->Config_kI(kSlotIDx_Motion, kI_MotionRight, kTimeoutMs);
     driveTrainRightFront->Config_kD(kSlotIDx_Motion, kD_MotionRight, kTimeoutMs);

}
